config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  root "pages#home"

  resource :session
  resources :passwords, param: :token
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Crooz" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Crooz">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <% if current_user %>
        <nav>
          <%= link_to "Timeline", timeline_path %>
          <% if current_user.croozer %>
            <%= link_to "Garage", croozer_path(current_user.croozer) %>
            <%= link_to "Refuels", croozer_refuels_path(current_user.croozer) %>
            <%= link_to "Tales", croozer_tales_path(current_user.croozer) %>
          <% else %>
            <%= link_to "Add car", new_croozer_path %>
          <% end %>
          <%= button_to "Sign out", session_path, method: :delete %>
        </nav>
      <% else %>
        <nav>
          <%= link_to "Sign in", new_session_path %>
          <%= link_to "Sign up", new_signup_path %>
        </nav>
      <% end %>
    </header>

    <% if flash[:notice] %>
      <p><%= flash[:notice] %></p>
    <% end %>

    <% if flash[:alert] %>
      <p><%= flash[:alert] %></p>
    <% end %>

    <%= yield %>
  </body>
</html>